# Clave única de identificación del proyecto
sonar.projectKey=proyecto_calidad_software

# Nombre del proyecto
sonar.projectName=proyecto_calidad_software


# Versión del proyecto
sonar.projectVersion=1.0

# Directorio donde está el código fuente
sonar.sources=.

# URL de SonarQube (asegúrate de que SonarQube está corriendo en localhost:9000)
sonar.host.url=http://localhost:9000

# Token de autenticación (puedes obtenerlo desde la interfaz web de SonarQube)
sonar.login=sqa_1e0b97edcf30529d9360985970ac03c94592a7ec